server {
    listen 80;

    # Global mapping for portals
    location /hospital_portal/ {
        alias /usr/share/nginx/html/hospital_portal/;
        index index.html;
    }

    location /doctor_portal/ {
        alias /usr/share/nginx/html/doctor_portal/;
        index index.html;
    }

    location /family_portal/ {
        alias /usr/share/nginx/html/family_portal/;
        index index.html;
    }

    # Root landing page for convenience
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
}
